# Generated by Django 3.0.3 on 2021-04-20 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210421_0106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Comment',
        ),
    ]
